controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    my_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    my_forward_position_controller:
      type: forward_command_controller/ForwardCommandController


my_forward_position_controller:
  ros__parameters:
    joints:
      - shoulder
      - elbow
    interface_name: position

# my_joint_state_broadcaster:
#   ros__parameters: