controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    lock_memory: false # necessary on RPi to prevent memory failures
    # use_sim_time: true

    my_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    my_ik_controller:
      type: base_package/IKController
      # type: joint_trajectory_controller/JointTrajectoryController


my_ik_controller:
  ros__parameters:
    joints:
      - shoulder
      - elbow
    interface_name: position

  # ros__parameters:
  #   joints:
  #     - shoulder
  #     - elbow

  #   command_interfaces:
  #     - position

  #   state_interfaces:
  #     - position

  #   action_monitor_rate: 20.0

  #   allow_partial_joints_goal: false
  #   open_loop_control: false
  #   allow_integration_in_goal_trajectories: true
  #   constraints:
  #     stopped_velocity_tolerance: 0.01
  #     goal_time: 0.0

# my_joint_state_broadcaster:
#   ros__parameters: