<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="square_prism_identical_collision" params="mass length height *material">
        <visual>
            <geometry>
                <box size="${height} ${length} ${height}"/>
            </geometry>
            <origin xyz="0 ${length/2} ${height/2}" />
            <xacro:insert_block name="material"/>
        </visual>
        <collision>
            <geometry>
                <box size="${height} ${length} ${height}"/>
            </geometry>
            <origin xyz="0 ${length/2} ${height/2}" />
        </collision>
    </xacro:macro>

    <xacro:macro name="cylinder_identical_collision" params="mass radius height *material">
        <visual>
            <geometry>
                <cylinder length="${height}" radius="${radius}"/>
            </geometry>
            <xacro:insert_block name="material"/>
            <origin xyz="0 0 ${height/2}"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${height}" radius="${radius}"/>
            </geometry>
            <origin xyz="0 0 ${height/2}"/>
        </collision>
    </xacro:macro>

</robot>