<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
    <xacro:macro name="square_prism_inertial" params="mass length height">
        <inertial>
            <mass value="${mass}"/>
            <!-- In the Articulated Robot video, his xyz here is x, 0, z. Why? -->
            <origin xyz="${height/2} ${length/2} ${height/2}" />
            <inertia ixx="${1/12 * mass * (length*length + height*height)}" ixy="0.0" ixz="0.0"
                    iyy="${1/12 * mass * (2 * height*height)}" iyz="0.0"
                    izz="${1/12 * mass * (length*length + height*height)}" />
        </inertial>
    </xacro:macro>

    

</robot>